2023-01-31 16:58:57,432 INFO    MainThread:29396 [wandb_setup.py:_flush():68] Configure stats pid to 29396
2023-01-31 16:58:57,432 INFO    MainThread:29396 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Abhinav\.config\wandb\settings
2023-01-31 16:58:57,432 INFO    MainThread:29396 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Abhinav\Desktop\RecSystem (1)\RecSystem\wandb\settings
2023-01-31 16:58:57,433 INFO    MainThread:29396 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-31 16:58:57,433 INFO    MainThread:29396 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\Abhinav\\Desktop\\RecSystem (1)\\RecSystem\\main.py'}
2023-01-31 16:58:57,433 INFO    MainThread:29396 [wandb_init.py:_log_setup():478] Logging user logs to C:\Users\Abhinav\Desktop\RecSystem (1)\RecSystem\wandb\run-20230131_165857-ug1dwfxv\logs\debug.log
2023-01-31 16:58:57,433 INFO    MainThread:29396 [wandb_init.py:_log_setup():479] Logging internal logs to C:\Users\Abhinav\Desktop\RecSystem (1)\RecSystem\wandb\run-20230131_165857-ug1dwfxv\logs\debug-internal.log
2023-01-31 16:58:57,435 INFO    MainThread:29396 [wandb_init.py:init():518] calling init triggers
2023-01-31 16:58:57,435 INFO    MainThread:29396 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.1, 'epochs': 200, 'batch_size': 128, 'architecture': 'MF'}
2023-01-31 16:58:57,435 INFO    MainThread:29396 [wandb_init.py:init():571] starting backend
2023-01-31 16:58:57,435 INFO    MainThread:29396 [wandb_init.py:init():575] setting up manager
2023-01-31 16:58:57,453 INFO    MainThread:29396 [wandb_init.py:init():582] backend started and connected
2023-01-31 16:58:57,468 INFO    MainThread:29396 [wandb_init.py:init():670] updated telemetry
2023-01-31 16:58:57,471 INFO    MainThread:29396 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-01-31 16:59:00,644 WARNING MsgRouterThr:29396 [router.py:message_loop():77] message_loop has been closed
2023-01-31 16:59:02,573 ERROR   MainThread:29396 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "C:\dev\Python\lib\site-packages\wandb\sdk\wandb_init.py", line 1108, in init
    run = wi.init()
  File "C:\dev\Python\lib\site-packages\wandb\sdk\wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "C:\dev\Python\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
